name: cz4071

channels:
  - defaults

dependencies:
  - python=3.9.7
  - pandas=1.3.5
  - beautifulsoup4=4.10.0
  - ipykernel=6.4.1
  - xlrd=2.0.1
  - requests=2.26.0
  - html5lib=1.1
  - tqdm=4.62.3
  - networkx=2.7.1
  - lxml=4.8.0
  - pyvis=0.1.9
  - openpyxl=3.0.9
  - streamlit=1.7.0
  - got=0.0.1
  - matplotlib=3.5.1
  - scipy=1.8.0
